site_name: lavalink hosting
site_author: DarrenOfficial
site_url: https://lavalink.darrennathanael.com
site_description: List of free lavalink servers! If you have lavalink that you can share feel free to make a pull request! Lavalink is a standalone audio sending node based on Lavaplayer and JDA-Audio. Allows for sending audio without it ever reaching any of your shards.
repo_name: 'lavalink list'
repo_url: 'https://github.com/DarrenOfficial/lavalink-list'
edit_uri: 'https://github.com/DarrenOfficial/lavalink-list/edit/main/docs'


theme:
  palette: 
    - scheme: slate 
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: 'teal'
      accent: 'green'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  name: 'material'
  custom_dir: overrides
  logo: 'https://cdn.darrennathanael.com/assets/java/springboot.svg'
  include_search_page: false
  search_index_only: true

  font:
    text: "Red Hat Text"
    code: "Roboto Mono"
  favicon:
    'https://cdn.darrennathanael.com/assets/lavalinklist/favicon.ico'
  features:
    - tabs
    - instantsite
    - navigation.tracking
    - navigation.expand
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Home: index.md
  - Lavalink with ssl: SSL/lavalink-with-ssl.md
  - Lavalink without ssl: NoSSL/lavalink-without-ssl.md
  - FAQs: FAQ/frequently-asked-questions.md
extra:
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/darrenuselinux'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/darrenofficial' 
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.darrennathanael.com'
  generator: false
copyright: 'Copyright &copy; Darren Nathanael'
plugins:
  - search
  - minify:
      minify_html: true
